version: '3.8'

services:
  face-recognition:
    build: .
    container_name: face_recognition_app
    devices:
      - "/dev/video0:/dev/video0"  # Acessa a câmera do host
    volumes:
      - "./saved_faces:/app/saved_faces"  # Monta o volume no host
    stdin_open: true  # Permite interação no terminal
    tty: true  # Modo interativo

